浪崎恭佑 EX1 解答 [python]
TakedaLab/B4Lecture-2024 pull request #13
Opened 2024-04-22 02:19 UTC by kyo73

# What

- wavfileからスペクトログラムを描画し、元に戻す
- 実行コマンド
 `B4Lecture-2024/k_namizaki/ex1/main1.py -file "wavfileの名前"`
 今回使用したwavfileはB4Lecture-2024\k_namizaki\ex1\recoMono.wav

# Result

FFT前
![Before](https://github.com/TakedaLab/B4Lecture-2024/assets/166796188/52d10508-f66b-467d-85c7-bd14ba5764c6)
スペクトログラム
![Spectrogram](https://github.com/TakedaLab/B4Lecture-2024/assets/166796188/63b09cd3-ef71-4a98-9a7f-d9a451053688)
IFFT後
![After](https://github.com/TakedaLab/B4Lecture-2024/assets/166796188/a530f991-502d-4182-ba3f-6e20f86cd8d6)

# WIP [オプション]

spectrogramの図があんまりきれいにならない。

# References [オプション]

参考　音声データをFFT解析してスペクトログラムを作成する方法
https://mori-memo.hateblo.jp/entry/2022/05/06/143456

2024-04-22 07:46 UTC, zodiac-18 commented on ex1/k_namizaki/main1.py
お疲れ様です．
非常に読みやすくて良いと思います！
以下コメントです．

2024-04-22 12:42 UTC, zodiac-18 requested changes
@kyo73 お疲れ様です！
全体的によく書けていると思います！
以下コメントです。

2024-04-22 12:42 UTC, zodiac-18 commented on ex1/k_namizaki/main1.py
> +    args = parser.parse_args()
argparseを使ってコマンドラインから変数を指定できるように工夫していて素晴らしいですね！
ファイル名だけでなくFFT関連のパラメータもコマンドラインから指定できるようにすると柔軟なプログラムになって良いと思います。
```suggestion
    parser = argparse.ArgumentParser(
        description="wavfileからスペクトログラムを描画し、元に戻す"
    )
    parser.add_argument("-file", help="ファイルを入力")
    parser.add_argument("-n_fft", help="FFTサイズ")
    parser.add_argument("-shift", help="ホップサイズ")
    args = parser.parse_args()
```

2024-04-22 12:42 UTC, zodiac-18 commented on ex1/k_namizaki/main1.py
> +    )
先にスペクトログラムの配列を確保してから代入するのは高速化の観点でとても良いですね！

2024-04-22 12:42 UTC, zodiac-18 commented on ex1/k_namizaki/main1.py
> +        spectrogram[:, i] = spectrum
この部分ですが、実はnumpy.lib.stride_tricksのas_strided関数を用いて先にフレーム系列を取得しておくとforループなしで書くことができます。→ [参考](https://qiita.com/daimonji-bucket/items/7d04a9687e7714d6216b)
難しい話なので必須ではないですが是非チャレンジしてみてください！

2024-04-22 12:42 UTC, zodiac-18 commented on ex1/k_namizaki/main1.py
全体的にですが、再利用性のためにmain関数一つにコードをまとめるのではなく、機能ごとに分割するとよいです。(スペクトログラムを作る関数、iSTFTをする関数など)
これらの関数は今後の課題で利用する可能性があるので今のうちにモジュールにしておきましょう。
例えば以下のような感じです。(docstringsも作って関数の説明をドキュメント化してください)
```python
def compute_spectrogram(data, n_fft=1024, hop_size=512):
"""
    """
    Create a spectrogram from an audio file.
    Parameters
    -------------
    data (ndarray) : 音声波形
    n_fft (int) : fftの窓幅
    hop_length (int) : ホップサイズ
    Returns
    ------------
    spectrogram (ndarray) : スペクトログラム
    """
"""
    ...
    # 略: スペクトログラムの計算
    return spectrogram
```

2024-04-23 07:06 UTC, yohei1273 reviewed
お疲れ様です！
argparseを使ってコマンドラインから値をとれるようにできることを知らなかったので、とても勉強になりました！
また窓関数も自分とは異なる方法で取得するなど、自分とは異なるコードが使われている部分も多く参考になりました！

2024-04-24 01:56 UTC, merged