Ex branti
TakedaLab/B4Lecture-2024 pull request #31
Opened 2024-05-06 00:58 UTC by kyo73

# What
第三回B4輪講課題の解答。
- 最小二乗法を用いて回帰分析を行う。
- 実行コマンド
 `$ python main3.py -file ファイルのパス -n 次数 -normal 正則化係数`

# Result
data1（次数１）
![data1-n1](https://github.com/TakedaLab/B4Lecture-2024/assets/166796188/3a1ec161-6989-475d-b729-10a408ad5227)
data2（次数３）
![data2-n3](https://github.com/TakedaLab/B4Lecture-2024/assets/166796188/c5b65f1b-ef9d-43b1-ab0e-fdcd1d580d59)
data3（次数３）
![data3-n3](https://github.com/TakedaLab/B4Lecture-2024/assets/166796188/190c702d-d229-4f4c-9676-1179dc43bec6)
![data3-n3(2)](https://github.com/TakedaLab/B4Lecture-2024/assets/166796188/11c03ba3-69f2-4df7-a126-d6214db3bfef)

正則化
data2（次数１５）
![data2-n15](https://github.com/TakedaLab/B4Lecture-2024/assets/166796188/b9cad176-ad39-4121-b661-12d6165c008e)
data2（次数１５）（正則化係数３）
![data2-n15-norm3](https://github.com/TakedaLab/B4Lecture-2024/assets/166796188/fe0a2fef-ac3f-463d-89eb-39104353e3b3)

# WIP [オプション]

図の中に式を入れたかったが、次数が高いときどうしようもない気がしたので、やめた

2024-05-07 01:45 UTC, KateSawada requested changes
丁寧なコメントがついていて，綺麗に実装されていると思いました! 可読性や高速化の観点でいくつかコメントをしたので，挑戦してみてください．

また，csvファイルについてですが，TakedaLab/B4Lecture-2024からmergeすることでファイルを持ってくることができます．同じファイルが複数存在するのは望ましくないため，今後は気をつけてみてください．ただファイルを消してcommitしても，「ファイルが作成された→ファイルが消された」という履歴が残ります．gitの履歴から抹消する（そもそも存在しなかったことにする）こともできますが，少し煩雑な手順を踏むため必須とはしませんが，やってみる場合は気をつけてください．

2024-05-07 01:45 UTC, KateSawada commented on ex3/k_namizaki/main3.py
> +    w : 重み
他の関数定義の箇所にも当てはまりますが，Docstringには型も書いておくと後々幸せになれるので推奨します．
いくつか主流のスタイルがありますが，GoogleスタイルかNumpyスタイルが使い勝手が良いと思います．[参考](https://qiita.com/flcn-x/items/393c6f1f1e1e5abec906)

Numpyスタイルで書くとこうなります．
データ型に，listやnumpy配列など，配列状のものを許容する場合はarray-likeと書くのが慣例だったと思います．
また，配列を引数に取る場合には，その形状を書いておくと良いです．2次元以上の配列を使う時，あとから混乱するのを防げます．

```suggestion
    Plot in 2 dimensions.

    Parameters
    ----------
    x (array-like): xのデータ. shape=(length)
    y (array-like): yのデータ. shape=(length)
    w (array-like): 重み. shape=(order)
```

2024-05-07 01:45 UTC, KateSawada commented on ex3/k_namizaki/main3.py
> +def plot2d(x, y, w):
関数の仮引数には，typing（型ヒント）を付けておくことをオススメします．[参考](https://docs.python.org/ja/3/library/typing.html)
これを付けておくと，VSCodeのsuggestionが働いてくれて，コーディングも捗ると思います．

```suggestion
from numpy.typing import ArrayLike

def plot2d(x: ArrayLike, y: ArrayLike, w: ArrayLike):
```

また，返り値を持つ場合や，デフォルト値を持つ関数の場合は以下のようになります．
```python
def hoge(arg1: int, arg2: str = "This Is Hoge") -> list[int]:
```

2024-05-07 01:45 UTC, KateSawada commented on ex3/k_namizaki/main3.py
> +        i += 1
ここの部分は，forループ無しで実装できます．pythonのループは遅いので，numpyの機能を使ってループをなくすことができると高速化できます．ここでは，numpyのブロードキャストを使うために，軸の追加をしています．

```suggestion
    X = x[:, np.newaxis] ** np.arange(degree + 1)[np.newaxis, :]
```

2024-05-07 01:45 UTC, KateSawada commented on ex3/k_namizaki/main3.py
> +        i += 1
ここも2dと同様に，forループを無くせます．余裕があれば考えてみてください．

2024-05-08 04:41 UTC, MiyajiHikari commented
コードを読んで、自分がnp.poly1dとnp.newaxisの使い方をあまり理解していないことが分かったので、今後の為に勉強しておきたいと思いました。

2024-05-08 05:33 UTC, KateSawada commented
@MiyajiHikari 
> コードを読んで、自分がnp.poly1dとnp.newaxisの使い方をあまり理解していないことが分かったので、今後の為に勉強しておきたいと思いました。

せっかくなので `np.newaxis` を用いた配列の形状変更についてちょびっと補足です．
```python
x = np.arange(10)

x1 = x.reshape(-1, len(x))  # (1, len(x)) でも同じ
x2 = x[np.newaxis, :]
```
このコードのx1, x2は全く同じ配列になります． `np.newaxis` は，「その次元に新しい軸（サイズ1）を追加する」と解釈するといいかもです．個人的にはreshapeよりも読みやすくなると思っています．
また， `np.newaxis` は `None` のエイリアス（ `np.newaxis is None` が `True`  になる）なので，置き換えても問題なく動作します．ただ，明示的に「新たな軸の追加操作」であることを書けるので，可読性の観点からこちらをオススメします．

2024-05-08 05:45 UTC, KateSawada requested changes

2024-05-08 05:45 UTC, KateSawada commented on ex3/k_namizaki/main3.py
> +    w = np.linalg.inv(X.T @ X + normal * Im) @ X.T @ Z
すいません，前回のreview時にここ見落としていました…
今の実装だと，例えばn=2を指定した時に， $z = a_0 + a_1 x + a_2 y + a_3 x^2 + a_4 y^2$ でフィッティングしていると思いますが， $z = a_0 + a_1 x + a_2 y + a_3 x^2 + a xy + a_4 y^2$ でフィッティングするようにしてみましょう．
つまり，一般化すると， $\Sigma_{k=0}^{n} \Sigma_{j=0}^{k} (a_{k, j} x^j y^{k-j})$ となります．

2024-05-14 04:48 UTC, KateSawada commented
@kyo73 遅くなってごめんなさい! 実装は問題ないと思います．xyなどの項への対応もfor文ナシで実装できるので，時間がある時に考えてみると面白いと思います．

これでapproveしようと思ったんですが，ブランチに問題がありそうなのでちょっと相談させてください

@SZucchini 一つのブランチで複数の演習をやっているようで，このPRをApproveすると，途中のEX4のものもmergeされそうです．ブランチはわけてもらったほうがいいでしょうか? （その場合，EX4に関するcommitをEX4用のブランチにcherry-pickで移動して，force pushしてもらう感じの対応をすることになるかと思います）

2024-05-14 04:50 UTC, KateSawada commented
@kyo73 それからもう一点今後の演習で意識してもらえると良いかなと思ったことを伝えます．commit messageの内容を充実させると，色々と幸せになれると思います．B4輪講では，reviewerがどのタイミングでreviewすればいいのかわからないので，commit messageに「何をやったか」を書いてもらえるとズムーズです．研究では，そのcommitでやったことを書いておくと，後から見直す必要が生まれた時に楽です（逆に，書いていないとそこそこ地獄を見ます←体験談）．

2024-05-14 09:09 UTC, kyo73 commented
ex4/k_namizakiの内容物を一回隔離して、pushすれば大丈夫ですか？

2024-05-15 03:15 UTC, KateSawada commented
@kyo73 
> ex4\k_namizakiの内容物を一回隔離して、pushすれば大丈夫ですか？

隔離の意味がよくわからなかったですが，git上での履歴を操作しないと問題があると思います．
[演習の進め方](https://github.com/TakedaLab/B4Lecture-2024?tab=readme-ov-file#%E6%BC%94%E7%BF%92%E3%81%AE%E9%80%B2%E3%82%81%E6%96%B9)では，演習ごとにブランチを分ける想定をしていて，それに従って自動化が組まれているようなので，以下の手順で対応をしてもらえると良いかと思います．

1. ex4開始前の状態から，ex_4のブランチを作成
2. 29d5e13以降のcommit（ex4に関わるもの全て）を，ex_4ブランチに移動（gitのcherry-pickコマンドを利用できます）
3. 今のex_branti上からex4に関わるcommitが削除されたことを確認
4. kyo73:ex_brantiにforce push

2024-05-15 03:17 UTC, KateSawada commented
@kyo73 
補足
上記の対応をすると，ex_4ブランチではex4のファイルが消えますが，d3502bfより前のcommitを参照することで，ファイルを削除する前の状態に遡ることができます．

2024-05-15 04:00 UTC, SZucchini commented
@KateSawada 
確認が遅れてごめんなさい。確かにEX3はEX3のみで分けるのがベストかと思います。
極論を言えば、EX4をmergeするときにconflictしなければ問題ないような気もしますが（1つのブランチで全ての課題をこなし続ける？）、管理しやすいのは課題毎にブランチを切る方法だと思います。

@kyo73 
澤田くんのアドバイスに従って、一度やってみてもらえますか？
ex4からはブランチを演習毎で切ってやってくれているようなので、もう問題は解決しているかもしれませんが…
もしわからないことがあれば今日のB4輪講後に僕か澤田くんに声をかけてください。

2024-05-15 04:21 UTC, KateSawada commented
@SZucchini 
> 1つのブランチで全ての課題をこなし続ける

これやると，今回みたいに前の課題のapprove前に次の課題のcommitをpushした時に，前の課題と一緒に次の課題が途中であってもmergeされてしまうので，今のB4輪講のreviewのスタイルとは相性が悪い気がします．

2024-05-18 07:02 UTC, KateSawada approved these changes
LGTM
すいません遅くなってしまいました

2024-05-21 12:46 UTC, merged