古田京平 EX1 解答 python
TakedaLab/B4Lecture-2024 pull request #4
Opened 2024-04-18 01:09 UTC by tour2st

出力結果は以下の通りです
![temp](https://github.com/TakedaLab/B4Lecture-2024/assets/141434313/5bc100aa-6eb8-4455-bf4d-4c2ea5aa80d5)

2024-04-18 09:02 UTC, mattsunkun commented
グラフを1:1:2で分割できるの知りませんでした．参考になります．

2024-04-19 09:03 UTC, KateSawada requested changes
@tour2st 
綺麗な実装でとても良いですね! いくつか読みやすくするためのヒントや，さらなる高速化のためのヒントを書きました．

2024-04-19 09:03 UTC, KateSawada commented on ex1/k_furuta/main.py
> +        signal[start : start + n_fft] += frame.real * np.hanning(n_fft)
spectrogramと同様，ループ無しで実装できます．
必須ではありませんが，時間があればぜひトライしてみてください!

2024-04-22 07:24 UTC, tour2st commented
コードレビューに沿って修正を行いました。
確認お願いします。

2024-04-22 07:34 UTC, KateSawada approved these changes
LGTM

2024-04-22 07:34 UTC, KateSawada commented on ex1/k_furuta/main.py
> +    # 復元した波形をwavファイルに再構成(なぜかノイズが発生している)
ぜひこの理由を考察してみてください!

2024-04-22 12:42 UTC, merged