add ex8
TakedaLab/B4Lecture-2024 pull request #71
Opened 2024-06-05 08:14 UTC by Rikuhei-ynwa

# What

ex8を作成しました
ご意見・ご確認いただけると幸いです。

# References [オプション]

[【徹底解説】VAEをはじめからていねいに](https://academ-aid.com/ml/vae)

2024-06-06 00:33 UTC, Rikuhei-ynwa commented
isortのコードチェッカーが何回やっても通らなくて困っています。
ターミナル上で
`poetry run isort main.py`
で整形したあとにcommit&pushしているのですが、、、

2024-06-06 06:42 UTC, Rikuhei-ynwa commented
やった！！！
通った！！！
@miuratakumiF4 さんありがとうございます！！！！

2024-06-10 12:20 UTC, SZucchini commented on ex8/.gitignore
> +# Byte-compiled / optimized / DLL files
imagesの不要な画像（READMEのデモに必要なもの以外？）はignoreした方が良いと思います。

2024-06-10 12:21 UTC, SZucchini commented on ex8/README.md
> +`pyproject.toml`に記載されているパッケージには開発環境のパッケージも含まれているため，自分の開発環境でやりたい場合は`poetry install --no-dev`を実行してください．
「開発環境のパッケージ」と言うより、「formatter（black, isort）が含まれる」と書いた方が伝わると思います。

2024-06-10 12:23 UTC, SZucchini commented on ex8/main.py
> +            print("-----Start training-----")
printで出力すると、サーバーにslurmでジョブを投げた際に学習が終わるまで出力が出ません。
学習が進んでいるのか確認が難しくなるので、好ましくないかも知れません（B4各自に修正を任せても良いかも）

2024-06-10 12:26 UTC, SZucchini requested changes
動作確認を終え、いくつかコメントを残しました。
imagesの不要なファイルをignoreする箇所については、修正対応をお願いします。
それ以外については対応を任せます。.gitignoreを修正してもらえたらMergeします。

2024-06-11 05:41 UTC, Rikuhei-ynwa commented
指摘された点を修正しました

2024-06-11 05:52 UTC, SZucchini approved these changes

2024-06-11 05:53 UTC, merged